perf: 添加storybook工作流测试

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -2,3 +2,43 @@
 . "$(dirname "$0")/_/husky.sh"
 #!调用commitlint校验提交格式
 npx commitlint --edit
+
+
+# 设置远程仓库的名称和URL
+REMOTE_URL="https://github.com/componentProject/vue-component-vite.git"
+MAIN_BRANCH="main"
+BRANCH_NAME="docs"
+REMOTE_NAME="vitepress"
+# 获取当前分支名称
+CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+
+# 判断当前分支并执行相应操作
+if [ "$CURRENT_BRANCH" = "$BRANCH_NAME" ]; then
+    echo "当前分支是 $BRANCH_NAME，正在切换到 $MAIN_BRANCH 分支并终止脚本..."
+    git checkout $MAIN_BRANCH
+    exit 0
+fi
+
+
+# 检查远程仓库是否存在
+if ! git remote | grep -qx "$REMOTE_NAME"; then
+    # 远程仓库不存在，添加它
+    echo "Remote '$REMOTE_NAME' not found. Adding it now."
+    git remote add "$REMOTE_NAME" "$REMOTE_URL"
+else
+    echo "Remote '$REMOTE_NAME' already exists."
+fi
+
+# 判断当前分支并执行相应操作
+if [ "$CURRENT_BRANCH" = "$BRANCH_NAME" ]; then
+    echo "当前分支是 $BRANCH_NAME，正在终止脚本..."
+elif git show-ref --verify --quiet refs/heads/$BRANCH_NAME; then
+    echo "分支 $BRANCH_NAME 存在，但当前不在该分支上，无需切换..."
+    # 推送更改到另一个远程仓库的指定分支
+    git push -f "$REMOTE_NAME" "$BRANCH_NAME"
+else
+    echo "分支 $BRANCH_NAME 不存在，正在创建并切换到该分支..."
+    git checkout -b $BRANCH_NAME
+    # 推送更改到另一个远程仓库的指定分支
+    git push -f "$REMOTE_NAME" "$BRANCH_NAME"
+fi
